### ISSUE TITLE
Extend python get/set methods

### ISSUE THREAD

**Issue by Shais2304** [CircleOf8/TemplePlus#1]
To support reading/writing non-32bit fields:
-64 bit fields
-float fields
-object handle fields
-256bit fields
-list fields

**Comment by shartte** [comment]
Can you point me to some example how 32-bit fields are currently being read?

**Comment by Shais2304** [comment]
The python function for getting 32bit fields is here:

.text:100B2F60 PyObj_Obj_Get_Int proc near             ; DATA XREF: .data:102CF06Co
.text:100B2F60
.text:100B2F60 nFieldIdx       = dword ptr -4
.text:100B2F60 pCaller         = dword ptr  4
.text:100B2F60 pPyTupleIn      = dword ptr  8

Internally it uses the function

.text:1009E1D0 ; int __cdecl Obj_Get_Internal_Field_32bit_Int(ObjHndl, _nFieldIdx)

(that's a wrapper or something like that, no?)

There's a whole bunch of Obj_Get_XXXX functions that should be similarly exposed.

**Comment by Shais2304** [comment]
This is mostly done, though I'd like to add a generic variant for Set_IdxField_byValue to support vararg
