### ISSUE TITLE
Make proper XP scaling

### ISSUE THREAD

**Issue by Shais2304** [CircleOf8/TemplePlus#6]
100B5700                         ; int __cdecl GiveXPRewards()

**Comment by shartte** [comment]
What would proper XP scaling look like? I honestly don't know how it works now, and how it would be supposed to work, heh. 
Should it depend on the game difficulty, maybe?

**Comment by Shais2304** [comment]
Oh I'm just talking about scaling XP rewards for character levels beyond 10. 
Currently we are faking it via script by reducing the monster's CR so that the XP reward is closer to what it should be, but that's far from optimal.
Anyway I'm recreating the above mentioned function. Nailing down the exact table generation rule is a bit tricky but I'm getting there :)

**Comment by Shais2304** [comment]
Done! We now have a proper working XP table up to level 20.

Remember to disable the CR reduction workaround in combat_standard_routines.py!!!
