### ISSUE TITLE
"Enlarge" spells roundoff errors cause characters to gradually shrink

### ISSUE THREAD

**Issue by Shais2304** [CircleOf8/TemplePlus#67]
Present in vanilla, but exacerbated by the different float->int library we use in TemplePlus.

**Comment by shartte** [comment]
Are you really sure this is the cause btw?
float->int is pretty stable across MSVC libraries i think.
The *order* of floating point operations however will influence the accuracy of your result.
At no point should floating point numbers be compared using ==, *that* will lead to errors such as this. Either always use an episolon for comparison or straight less than/greater than.

**Comment by Shais2304** [comment]
Well the fact is I have observed different behavior in TP vs. Vanilla, for functions we haven't touched.

Either way I have converted the floating point operations to integer multiplication / division -> instead of 1.8 I multiply by 9 and divide by 5 and vice versa.

This still results in some roundoff (ultimately to the next lowest multiple of 5) but that's acceptable I think without complicating things.
