### ISSUE TITLE
Multiselect broken

### ISSUE THREAD

**Issue by Shais2304** [CircleOf8/TemplePlus#8]
When casting a spell with multiselect (such as Cure Light Wounds, Mass) it initiates the casting sequences after selecting the first target. I'm guessing it has to do with mouse stuff (this is a new bug).

**Comment by shartte** [comment]
Have you ever tested this in old ToEE with windowed mode activated?

**Comment by Shais2304** [comment]
Whoops, silly me, I didn't notice I was testing with a level 1 character. It's working fine!
